### ISSUE TITLE
Disable CURLOPT_FOLLOWLOCATION at PROCERGS

### ISSUE THREAD

**Issue by guilhermednt** [PROCERGS/login-cidadao#667]
CURLOPT_FOLLOWLOCATION must be disabled at PROCERGS.

The following has to be added to the `config.yml` file:

``` yml
circle_rest_client:
    curl:
        defaults:
            CURLOPT_FOLLOWLOCATION: false
```
